[env]
upload_speed = 921600

[platformio]
default_envs = kyk_deltalight

[env:kyk_deltalight]
extends = esp32c3
platform = ${esp32c3.platform}
platform_packages = ${esp32c3.platform_packages}
framework = arduino
board = esp32-c3-devkitm-1
board_build.partitions = ${esp32.default_partitions}
upload_speed = 460800
build_unflags = ${common.build_unflags}
lib_deps = ${esp32c3.lib_deps}
build_flags = ${common.build_flags} ${esp32c3.build_flags} -D WLED_RELEASE_NAME=\"ESP32-C3\"
  -D WLED_WATCHDOG_TIMEOUT=0
  -DLOLIN_WIFI_FIX ; seems to work much better with this
  -DARDUINO_USB_CDC_ON_BOOT=1 ;; for virtual CDC USB
  ;-DARDUINO_USB_CDC_ON_BOOT=0   ;; for serial-to-USB chip
  -D WLED_DISABLE_INFRARED
  -D WLED_DISABLE_HUESYNC
  -D WLED_DISABLE_MQTT
  -D WLED_DISABLE_LOXONE
  -D WLED_DISABLE_ESPNOW
  -D WLED_DISABLE_OTA
  -D LIGHT_NAME="\"DeltaLight\""
  -D WLED_PRODUCT_NAME=LIGHT_NAME
  -D MDNS_NAME=LIGHT_NAME
  -D SERVERNAME=LIGHT_NAME
  -D USERMOD_MULTI_RELAY
  -D MULTI_RELAY_PINS=7,8
  -D MULTI_RELAY_DELAYS=0,0
  -D MULTI_RELAY_EXTERNALS=false,true
  -D MULTI_RELAY_INVERTS=false,false
  -D BTNPIN=9,2
  -D BTNTYPE=BTN_TYPE_PUSH,BTN_TYPE_PUSH
  -D DATA_PINS=10,3,4,5
  -D PIXEL_COUNTS=165,1,1,1
  -D LED_TYPES=TYPE_WS2812_RGB,TYPE_ANALOG_1CH,TYPE_ANALOG_1CH,TYPE_ANALOG_1CH
  -D WLED_PWM_FREQ=1000
  -D ABL_MILLIAMPS_DEFAULT=0
  -D WLED_AUTOSEGMENTS=1

; Boot Preset : {"on":true,"bri":64,"tt":5,"mainseg":0,"seg":[{"id":0,"start":165,"stop":168,"bri":255,"col":[[0,0,0,255],[0,0,0,0],[0,0,0,0]]},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}],"nl":{"on":true,"dur":1,"mode":1}}

[env:kyk_diamondlight]
board = esp32dev
platform = ${esp32.platform}
platform_packages = ${esp32.platform_packages}
lib_deps = ${esp32.lib_deps}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp32.build_flags} -D WLED_RELEASE_NAME=\"ESP32\"
  -D NDEBUG
  -D DEBUG
  -D DEBUG=1 -D WLED_DEBUG
  -D USERMOD_MULTI_RELAY
  -D WLED_DISABLE_INFRARED
  -D WLED_DISABLE_HUESYNC
  -D WLED_DISABLE_MQTT
  -D WLED_DISABLE_LOXONE
  -D WLED_DISABLE_ESPNOW
  -D WLED_DISABLE_OTA
  -D DATA_PINS=18,17,16,4
  -D PIXEL_COUNTS=120,1,1,1
  -D LED_TYPES=TYPE_WS2812_RGB,TYPE_ANALOG_1CH,TYPE_ANALOG_1CH,TYPE_ANALOG_1CH
  -D BTNPIN=33,25,5
  -D BTNTYPE=BTN_TYPE_PUSH,BTN_TYPE_PUSH,BTN_TYPE_PUSH
  -D MULTI_RELAY_PINS=13,21,14
  -D MULTI_RELAY_DELAYS=0,0,0
  -D MULTI_RELAY_EXTERNALS=false,false,true
  -D MULTI_RELAY_INVERTS=true,false,false
  -D LIGHT_NAME="\"DiamondLight\""
  -D WLED_PRODUCT_NAME=LIGHT_NAME
  -D MDNS_NAME=LIGHT_NAME
  -D SERVERNAME=LIGHT_NAME
